### ISSUE TITLE
CICD for DataBase Scorer

### ISSUE THREAD

**Issue by surenH2oai** [h2oai/dai-deployment-examples#13]
Database Scorer:
     This connects to a database using JDBC and can score and update the database. Very fast, one of our customers is doing 50K per second in production.

     Two versions of the code in the Distribution directory, DAIMojoRunner_DB.jar and DAIMojoRunner_DB_single.jar ideally I would like to just send "single" as its my more current version and has some new features.

     Link and documentation: https://github.com/h2oai/sales-engineering/tree/master/eric/DAI-Mojo-DB

**Comment by mmalohlava** [comment]
since it is in done, i am closing this issue.
